# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExpectationStubs.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx

